Config = Config or {}

Config.InteractionKey = 38 -- E
Config.OpenPrompt = 'Press ~INPUT_CONTEXT~ to browse dealership inventory'
Config.AutoCloseDistance = 9.0
Config.PurchaseCooldownMs = 1750
Config.AdminCustomPurchaseAce = 'lsrp.vehicleshop.admin'
Config.AdminCustomUnlistedPrice = 0
Config.VehicleSalesRevenueLicense = 'business:vehiclesales'

Config.Marker = {
    enabled = true,
    type = 36,
    scale = vector3(0.85, 0.85, 0.85),
    color = { r = 255, g = 176, b = 46, a = 185 },
    bobUpAndDown = true,
    rotate = true
}

Config.DefaultDeliveryParkingZone = 'Legion Square'

Config.Plate = {
    prefix = 'LS',
    letters = 2,
    numbers = 3
}

Config.Categories = {
    { id = 'compact', label = 'Compact' },
    { id = 'sedan', label = 'Sedan' },
    { id = 'muscle', label = 'Muscle' },
    { id = 'sports', label = 'Sports' },
    { id = 'suv', label = 'SUV' },
    { id = 'offroad', label = 'Off-road' },
    { id = 'motorcycle', label = 'Motorcycle' }
}

Config.Shops = {
    {
        id = 'pdm',
        name = 'Premium Deluxe Motorsport',
        subtitle = 'Curated city inventory with garage delivery.',
        interaction = vector3(-56.86, -1096.75, 26.42),
        interactionRadius = 2.8,
        drawDistance = 25.0,
        deliveryParkingZone = 'PDM',
        allowedCategories = {
            'compact',
            'sedan',
            'muscle',
            'sports',
            'suv',
            'offroad',
            'motorcycle'
        },
        demoDisplays = {
            { model = 'asbo', x = -36.71, y = -1101.38, z = 26.42, heading = 159.44 },
            { model = 'blista', x = -43.75, y = -1095.79, z = 26.42, heading = 71.12 },
            { model = 'prairie', x = -48.01, y = -1099.62, z = 26.42, heading = 214.52 }
        },
        blip = {
            enabled = true,
            sprite = 326,
            color = 5,
            scale = 0.85,
            label = 'Vehicle Dealership'
        }
    }
}

local VEHICLE_CATEGORY_DEFAULTS = {
    compact = { price = 18000, speed = 4, accel = 4, handling = 5, braking = 4 },
    sedan = { price = 32000, speed = 5, accel = 4, handling = 5, braking = 5 },
    muscle = { price = 62000, speed = 7, accel = 7, handling = 6, braking = 5 },
    sports = { price = 110000, speed = 8, accel = 8, handling = 7, braking = 6 },
    suv = { price = 84000, speed = 6, accel = 6, handling = 5, braking = 5 },
    offroad = { price = 72000, speed = 6, accel = 5, handling = 6, braking = 5 },
    motorcycle = { price = 52000, speed = 8, accel = 8, handling = 7, braking = 6 }
}

local function vehicleEntry(model, label, category, overrides)
    local defaults = VEHICLE_CATEGORY_DEFAULTS[category] or {}
    local entry = {
        model = model,
        label = label,
        category = category,
        price = math.max(0, math.floor(tonumber(defaults.price) or 0)),
        speed = math.max(0, math.floor(tonumber(defaults.speed) or 0)),
        accel = math.max(0, math.floor(tonumber(defaults.accel) or 0)),
        handling = math.max(0, math.floor(tonumber(defaults.handling) or 0)),
        braking = math.max(0, math.floor(tonumber(defaults.braking) or 0))
    }

    if type(overrides) == 'table' then
        for key, value in pairs(overrides) do
            entry[key] = value
        end
    end

    return entry
end

Config.Vehicles = {
    { model = 'asbo', label = 'Asbo', category = 'compact', price = 18000, speed = 4, accel = 5, handling = 6, braking = 5 },
    { model = 'blista', label = 'Blista', category = 'compact', price = 14000, speed = 4, accel = 4, handling = 5, braking = 4 },
    { model = 'prairie', label = 'Prairie', category = 'compact', price = 17000, speed = 5, accel = 4, handling = 5, braking = 5 },
    vehicleEntry('brioso', 'Brioso R/A', 'compact'),
    vehicleEntry('brioso2', 'Brioso 300', 'compact'),
    vehicleEntry('club', 'Club', 'compact'),
    vehicleEntry('dilettante', 'Dilettante', 'compact'),
    vehicleEntry('issi2', 'Issi', 'compact'),
    vehicleEntry('issi3', 'Issi Classic', 'compact'),
    vehicleEntry('kanjo', 'Blista Kanjo', 'compact'),
    vehicleEntry('panto', 'Panto', 'compact'),
    vehicleEntry('rhapsody', 'Rhapsody', 'compact'),
    vehicleEntry('weevil', 'Weevil', 'compact'),

    { model = 'primo', label = 'Primo', category = 'sedan', price = 26000, speed = 4, accel = 4, handling = 5, braking = 5 },
    { model = 'stanier', label = 'Stanier', category = 'sedan', price = 29000, speed = 5, accel = 4, handling = 5, braking = 5 },
    { model = 'tailgater', label = 'Tailgater', category = 'sedan', price = 42000, speed = 6, accel = 6, handling = 6, braking = 6 },
    vehicleEntry('asea', 'Asea', 'sedan'),
    vehicleEntry('asterope', 'Asterope', 'sedan'),
    vehicleEntry('asterope2', 'Asterope GZ', 'sedan'),
    vehicleEntry('cinquemila', 'Cinquemila', 'sedan'),
    vehicleEntry('cog55', 'Cognoscenti 55', 'sedan'),
    vehicleEntry('cognoscenti', 'Cognoscenti', 'sedan'),
    vehicleEntry('deity', 'Deity', 'sedan'),
    vehicleEntry('emperor', 'Emperor', 'sedan'),
    vehicleEntry('fugitive', 'Fugitive', 'sedan'),
    vehicleEntry('glendale', 'Glendale', 'sedan'),
    vehicleEntry('hardy', 'Hardy', 'sedan'),
    vehicleEntry('impaler5', 'Impaler SZ', 'sedan'),
    vehicleEntry('ingot', 'Ingot', 'sedan'),
    vehicleEntry('intruder', 'Intruder', 'sedan'),
    vehicleEntry('minimus', 'Minimus', 'sedan'),
    vehicleEntry('premier', 'Premier', 'sedan'),
    vehicleEntry('regina', 'Regina', 'sedan'),
    vehicleEntry('rhinehart', 'Rhinehart', 'sedan'),
    vehicleEntry('schafter2', 'Schafter', 'sedan'),
    vehicleEntry('stafford', 'Stafford', 'sedan'),
    vehicleEntry('stratum', 'Stratum', 'sedan'),
    vehicleEntry('superd', 'Super Diamond', 'sedan'),
    vehicleEntry('surge', 'Surge', 'sedan'),
    vehicleEntry('tailgater2', 'Tailgater S', 'sedan'),
    vehicleEntry('warrener', 'Warrener', 'sedan'),
    vehicleEntry('washington', 'Washington', 'sedan'),

    { model = 'dominator', label = 'Dominator', category = 'muscle', price = 54000, speed = 7, accel = 7, handling = 5, braking = 5 },
    { model = 'gauntlet', label = 'Gauntlet', category = 'muscle', price = 62000, speed = 7, accel = 6, handling = 6, braking = 5 },
    { model = 'buffalo', label = 'Buffalo', category = 'muscle', price = 68000, speed = 7, accel = 7, handling = 6, braking = 6 },
    vehicleEntry('blade', 'Blade', 'muscle'),
    vehicleEntry('broadway', 'Broadway', 'muscle'),
    vehicleEntry('buccaneer', 'Buccaneer', 'muscle'),
    vehicleEntry('buffalo4', 'Buffalo STX', 'muscle'),
    vehicleEntry('buffalo5', 'Buffalo EVX', 'muscle'),
    vehicleEntry('chino', 'Chino', 'muscle'),
    vehicleEntry('clique', 'Clique', 'muscle'),
    vehicleEntry('coquette3', 'Coquette BlackFin', 'muscle'),
    vehicleEntry('deviant', 'Deviant', 'muscle'),
    vehicleEntry('dominator3', 'Dominator GTX', 'muscle'),
    vehicleEntry('dominator7', 'Dominator ASP', 'muscle'),
    vehicleEntry('dominator8', 'Dominator GTT', 'muscle'),
    vehicleEntry('dominator9', 'Dominator GT', 'muscle'),
    vehicleEntry('dukes', 'Dukes', 'muscle'),
    vehicleEntry('ellie', 'Ellie', 'muscle'),
    vehicleEntry('eudora', 'Eudora', 'muscle'),
    vehicleEntry('faction', 'Faction', 'muscle'),
    vehicleEntry('gauntlet3', 'Gauntlet Classic', 'muscle'),
    vehicleEntry('gauntlet4', 'Gauntlet Hellfire', 'muscle'),
    vehicleEntry('greenwood', 'Greenwood', 'muscle'),
    vehicleEntry('hermes', 'Hermes', 'muscle'),
    vehicleEntry('hustler', 'Hustler', 'muscle'),
    vehicleEntry('impaler', 'Impaler', 'muscle'),
    vehicleEntry('impaler6', 'Impaler LX', 'muscle'),
    vehicleEntry('nightshade', 'Nightshade', 'muscle'),
    vehicleEntry('phoenix', 'Phoenix', 'muscle'),
    vehicleEntry('picador', 'Picador', 'muscle'),
    vehicleEntry('ruiner', 'Ruiner', 'muscle'),
    vehicleEntry('ruiner3', 'Ruiner', 'muscle'),
    vehicleEntry('ruiner4', 'Ruiner ZZ-8', 'muscle'),
    vehicleEntry('sabregt', 'Sabre Turbo', 'muscle'),
    vehicleEntry('stalion', 'Stallion', 'muscle'),
    vehicleEntry('tahoma', 'Tahoma Coupe', 'muscle'),
    vehicleEntry('tampa', 'Tampa', 'muscle'),
    vehicleEntry('tampa4', 'Tampa GT', 'muscle'),
    vehicleEntry('tulip', 'Tulip', 'muscle'),
    vehicleEntry('tulip2', 'Tulip M-100', 'muscle'),
    vehicleEntry('vamos', 'Vamos', 'muscle'),
    vehicleEntry('vigero', 'Vigero', 'muscle'),
    vehicleEntry('vigero2', 'Vigero ZX', 'muscle'),
    vehicleEntry('vigero3', 'Vigero ZX Convertible', 'muscle'),
    vehicleEntry('virgo', 'Virgo', 'muscle'),
    vehicleEntry('virgo3', 'Virgo Classic', 'muscle'),
    vehicleEntry('voodoo2', 'Voodoo', 'muscle'),
    vehicleEntry('yosemite', 'Yosemite', 'muscle'),

    { model = 'elegy2', label = 'Elegy RH8', category = 'sports', price = 88000, speed = 8, accel = 8, handling = 7, braking = 6 },
    { model = 'jester', label = 'Jester', category = 'sports', price = 112000, speed = 9, accel = 8, handling = 8, braking = 7 },
    { model = 'sultan', label = 'Sultan', category = 'sports', price = 94000, speed = 8, accel = 7, handling = 7, braking = 6 },
    { model = 'comet2', label = 'Comet', category = 'sports', price = 129000, speed = 9, accel = 8, handling = 8, braking = 7 },
    vehicleEntry('alpha', 'Alpha', 'sports'),
    vehicleEntry('banshee', 'Banshee', 'sports'),
    vehicleEntry('bestiagts', 'Bestia GTS', 'sports'),
    vehicleEntry('blista2', 'Blista Compact', 'sports'),
    vehicleEntry('buffalo2', 'Buffalo S', 'sports'),
    vehicleEntry('calico', 'Calico GTF', 'sports'),
    vehicleEntry('carbonizzare', 'Carbonizzare', 'sports'),
    vehicleEntry('comet5', 'Comet SR', 'sports'),
    vehicleEntry('comet6', 'Comet S2', 'sports'),
    vehicleEntry('comet7', 'Comet S2 Cabrio', 'sports'),
    vehicleEntry('coquette', 'Coquette', 'sports'),
    vehicleEntry('coquette4', 'Coquette D10', 'sports'),
    vehicleEntry('corsita', 'Corsita', 'sports'),
    vehicleEntry('coureur', 'La Coureuse', 'sports'),
    vehicleEntry('cypher', 'Cypher', 'sports'),
    vehicleEntry('drafter', '8F Drafter', 'sports'),
    vehicleEntry('euros', 'Euros', 'sports'),
    vehicleEntry('feltzer2', 'Feltzer', 'sports'),
    vehicleEntry('flashgt', 'Flash GT', 'sports'),
    vehicleEntry('furoregt', 'Furore GT', 'sports'),
    vehicleEntry('fusilade', 'Fusilade', 'sports'),
    vehicleEntry('futo', 'Futo', 'sports'),
    vehicleEntry('futo2', 'Futo GTX', 'sports'),
    vehicleEntry('gb200', 'GB200', 'sports'),
    vehicleEntry('growler', 'Growler', 'sports'),
    vehicleEntry('imorgon', 'Imorgon', 'sports'),
    vehicleEntry('issi7', 'Issi Sport', 'sports'),
    vehicleEntry('italigto', 'Itali GTO', 'sports'),
    vehicleEntry('italirsx', 'Itali RSX', 'sports'),
    vehicleEntry('jester3', 'Jester Classic', 'sports'),
    vehicleEntry('jester4', 'Jester RR', 'sports'),
    vehicleEntry('jugular', 'Jugular', 'sports'),
    vehicleEntry('khamelion', 'Khamelion', 'sports'),
    vehicleEntry('komoda', 'Komoda', 'sports'),
    vehicleEntry('kuruma', 'Kuruma', 'sports'),
    vehicleEntry('locust', 'Locust', 'sports'),
    vehicleEntry('lynx', 'Lynx', 'sports'),
    vehicleEntry('massacro', 'Massacro', 'sports'),
    vehicleEntry('neo', 'Neo', 'sports'),
    vehicleEntry('neon', 'Neon', 'sports'),
    vehicleEntry('ninef', '9F', 'sports'),
    vehicleEntry('ninef2', '9F Cabrio', 'sports'),
    vehicleEntry('omnisegt', 'Omnis e-GT', 'sports'),
    vehicleEntry('panthere', 'Panthere', 'sports'),
    vehicleEntry('paragon', 'Paragon R', 'sports'),
    vehicleEntry('pariah', 'Pariah', 'sports'),
    vehicleEntry('penumbra', 'Penumbra', 'sports'),
    vehicleEntry('penumbra2', 'Penumbra FF', 'sports'),
    vehicleEntry('r300', '300R', 'sports'),
    vehicleEntry('raiden', 'Raiden', 'sports'),
    vehicleEntry('rapidgt', 'Rapid GT', 'sports'),
    vehicleEntry('rapidgt2', 'Rapid GT', 'sports'),
    vehicleEntry('rapidgt4', 'Rapid GT X', 'sports'),
    vehicleEntry('remus', 'Remus', 'sports'),
    vehicleEntry('revolter', 'Revolter', 'sports'),
    vehicleEntry('rt3000', 'RT3000', 'sports'),
    vehicleEntry('ruston', 'Ruston', 'sports'),
    vehicleEntry('schafter3', 'Schafter V12', 'sports'),
    vehicleEntry('schafter4', 'Schafter LWB', 'sports'),
    vehicleEntry('schlagen', 'Schlagen GT', 'sports'),
    vehicleEntry('schwarzer', 'Schwartzer', 'sports'),
    vehicleEntry('sentinel3', 'Sentinel', 'sports'),
    vehicleEntry('sentinel5', 'Sentinel GTS', 'sports'),
    vehicleEntry('seven70', 'Seven-70', 'sports'),
    vehicleEntry('sm722', 'SM722', 'sports'),
    vehicleEntry('specter', 'Specter', 'sports'),
    vehicleEntry('stingertt', 'Itali GTO Stinger TT', 'sports'),
    vehicleEntry('streiter', 'Streiter', 'sports'),
    vehicleEntry('sugoi', 'Sugoi', 'sports'),
    vehicleEntry('sultan2', 'Sultan Classic', 'sports'),
    vehicleEntry('sultan3', 'Sultan RS Classic', 'sports'),
    vehicleEntry('surano', 'Surano', 'sports'),
    vehicleEntry('tenf', '10F', 'sports'),
    vehicleEntry('vectre', 'Vectre', 'sports'),
    vehicleEntry('verlierer2', 'Verlierer', 'sports'),
    vehicleEntry('vstr', 'V-STR', 'sports'),
    vehicleEntry('zr350', 'ZR350', 'sports'),

    { model = 'baller2', label = 'Baller', category = 'suv', price = 72000, speed = 6, accel = 6, handling = 5, braking = 5 },
    { model = 'rebla', label = 'Rebla GTS', category = 'suv', price = 98000, speed = 7, accel = 7, handling = 6, braking = 6 },
    { model = 'granger', label = 'Granger', category = 'suv', price = 84000, speed = 6, accel = 5, handling = 5, braking = 5 },
    vehicleEntry('aleutian', 'Aleutian', 'suv'),
    vehicleEntry('astron', 'Astron', 'suv'),
    vehicleEntry('baller', 'Baller', 'suv'),
    vehicleEntry('baller3', 'Baller LE', 'suv'),
    vehicleEntry('baller4', 'Baller LE LWB', 'suv'),
    vehicleEntry('baller7', 'Baller ST', 'suv'),
    vehicleEntry('baller8', 'Baller ST-D', 'suv'),
    vehicleEntry('bjxl', 'BeeJay XL', 'suv'),
    vehicleEntry('cavalcade', 'Cavalcade', 'suv'),
    vehicleEntry('cavalcade2', 'Cavalcade', 'suv'),
    vehicleEntry('cavalcade3', 'Cavalcade XL', 'suv'),
    vehicleEntry('contender', 'Contender', 'suv'),
    vehicleEntry('dorado', 'Dorado', 'suv'),
    vehicleEntry('dubsta', 'Dubsta', 'suv'),
    vehicleEntry('dubsta2', 'Dubsta', 'suv'),
    vehicleEntry('fq2', 'FQ 2', 'suv'),
    vehicleEntry('granger2', 'Granger 3600LX', 'suv'),
    vehicleEntry('gresley', 'Gresley', 'suv'),
    vehicleEntry('habanero', 'Habanero', 'suv'),
    vehicleEntry('huntley', 'Huntley S', 'suv'),
    vehicleEntry('iwagen', 'I-Wagen', 'suv'),
    vehicleEntry('jubilee', 'Jubilee', 'suv'),
    vehicleEntry('landstalker', 'Landstalker', 'suv'),
    vehicleEntry('landstalker2', 'Landstalker XL', 'suv'),
    vehicleEntry('novak', 'Novak', 'suv'),
    vehicleEntry('patriot', 'Patriot', 'suv'),
    vehicleEntry('radi', 'Radius', 'suv'),
    vehicleEntry('rocoto', 'Rocoto', 'suv'),
    vehicleEntry('seminole', 'Seminole', 'suv'),
    vehicleEntry('seminole2', 'Seminole Frontier', 'suv'),
    vehicleEntry('serrano', 'Serrano', 'suv'),
    vehicleEntry('toros', 'Toros', 'suv'),
    vehicleEntry('vivanite', 'Vivanite', 'suv'),
    vehicleEntry('woodlander', 'Woodlander', 'suv'),
    vehicleEntry('xls', 'XLS', 'suv'),

    { model = 'mesa', label = 'Mesa', category = 'offroad', price = 64000, speed = 6, accel = 6, handling = 6, braking = 5 },
    { model = 'sandking', label = 'Sandking XL', category = 'offroad', price = 79000, speed = 6, accel = 5, handling = 6, braking = 5 },
    vehicleEntry('bfinjection', 'Injection', 'offroad'),
    vehicleEntry('bifta', 'Bifta', 'offroad'),
    vehicleEntry('blazer', 'Blazer', 'offroad'),
    vehicleEntry('bodhi2', 'Bodhi', 'offroad'),
    vehicleEntry('boor', 'Boor', 'offroad'),
    vehicleEntry('brawler', 'Brawler', 'offroad'),
    vehicleEntry('caracara', 'Caracara', 'offroad'),
    vehicleEntry('caracara2', 'Caracara 4x4', 'offroad'),
    vehicleEntry('dloader', 'Duneloader', 'offroad'),
    vehicleEntry('draugur', 'Draugur', 'offroad'),
    vehicleEntry('dune', 'Dune Buggy', 'offroad'),
    vehicleEntry('freecrawler', 'Freecrawler', 'offroad'),
    vehicleEntry('hellion', 'Hellion', 'offroad'),
    vehicleEntry('kalahari', 'Kalahari', 'offroad'),
    vehicleEntry('kamacho', 'Kamacho', 'offroad'),
    vehicleEntry('l35', 'Walton L35', 'offroad'),
    vehicleEntry('l352', 'Walton L35 Stock', 'offroad'),
    vehicleEntry('rancherxl', 'Rancher XL', 'offroad'),
    vehicleEntry('rancherxl2', 'Rancher XL', 'offroad'),
    vehicleEntry('rebel', 'Rusty Rebel', 'offroad'),
    vehicleEntry('rebel2', 'Rebel', 'offroad'),
    vehicleEntry('riata', 'Riata', 'offroad'),
    vehicleEntry('sandking2', 'Sandking SWB', 'offroad'),
    vehicleEntry('terminus', 'Terminus', 'offroad'),
    vehicleEntry('yosemite3', 'Yosemite Rancher', 'offroad'),

    { model = 'faggio', label = 'Faggio', category = 'motorcycle', price = 7000, speed = 3, accel = 3, handling = 4, braking = 4 },
    { model = 'akuma', label = 'Akuma', category = 'motorcycle', price = 56000, speed = 8, accel = 8, handling = 7, braking = 6 },
    { model = 'bati', label = 'Bati 801', category = 'motorcycle', price = 68000, speed = 9, accel = 9, handling = 7, braking = 6 },
    vehicleEntry('avarus', 'Avarus', 'motorcycle'),
    vehicleEntry('bagger', 'Bagger', 'motorcycle'),
    vehicleEntry('bati2', 'Bati 801RR', 'motorcycle'),
    vehicleEntry('bf400', 'BF400', 'motorcycle'),
    vehicleEntry('carbonrs', 'Carbon RS', 'motorcycle'),
    vehicleEntry('cliffhanger', 'Cliffhanger', 'motorcycle'),
    vehicleEntry('daemon', 'Daemon', 'motorcycle'),
    vehicleEntry('defiler', 'Defiler', 'motorcycle'),
    vehicleEntry('diablous', 'Diabolus', 'motorcycle'),
    vehicleEntry('double', 'Double-T', 'motorcycle'),
    vehicleEntry('enduro', 'Enduro', 'motorcycle'),
    vehicleEntry('esskey', 'Esskey', 'motorcycle'),
    vehicleEntry('faggio2', 'Faggio', 'motorcycle'),
    vehicleEntry('faggio3', 'Faggio Mod', 'motorcycle'),
    vehicleEntry('fcr', 'FCR 1000', 'motorcycle'),
    vehicleEntry('hakuchou', 'Hakuchou', 'motorcycle'),
    vehicleEntry('hakuchou2', 'Hakuchou Drag', 'motorcycle'),
    vehicleEntry('hexer', 'Hexer', 'motorcycle'),
    vehicleEntry('innovation', 'Innovation', 'motorcycle'),
    vehicleEntry('lectro', 'Lectro', 'motorcycle'),
    vehicleEntry('manchez', 'Manchez', 'motorcycle'),
    vehicleEntry('manchez2', 'Manchez Scout', 'motorcycle'),
    vehicleEntry('nemesis', 'Nemesis', 'motorcycle'),
    vehicleEntry('nightblade', 'Nightblade', 'motorcycle'),
    vehicleEntry('pcj', 'PCJ 600', 'motorcycle'),
    vehicleEntry('powersurge', 'Powersurge', 'motorcycle'),
    vehicleEntry('reever', 'Reever', 'motorcycle'),
    vehicleEntry('ruffian', 'Ruffian', 'motorcycle'),
    vehicleEntry('sanchez2', 'Sanchez', 'motorcycle'),
    vehicleEntry('shinobi', 'Shinobi', 'motorcycle'),
    vehicleEntry('thrust', 'Thrust', 'motorcycle'),
    vehicleEntry('vader', 'Vader', 'motorcycle'),
    vehicleEntry('vindicator', 'Vindicator', 'motorcycle'),
    vehicleEntry('vortex', 'Vortex', 'motorcycle'),
    vehicleEntry('wolfsbane', 'Wolfsbane', 'motorcycle'),
    vehicleEntry('zombiea', 'Zombie Bobber', 'motorcycle'),
    vehicleEntry('zombieb', 'Zombie Chopper', 'motorcycle')
}
